# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: false
  JavaScript: true
  PHP: true
  Python: false
exclude_paths:
# excluding of main repository paths from Code climate
- "uploads/*"
- "uploads_varified/*"
- "db/*"
# excluding of api path
- "api/NotORM/*"
- "api/Slim/*"
# excluding paths of seller directory
- "seller/vendor/*"
- "seller/api/*"
- "seller/psd/*"
- "seller/l10n/*"
- "seller/fonts/*"
- "seller/img/*"
- "seller/js/directives/*"
- "seller/js/app/*"
- "seller/js/services/*"
- "seller/js/others/*"
- "seller/js/controllers/bootstrap.js"

# excluding paths of mzin_site directory
- "main_site/vendor/*"
- "main_site/data/*"
- "main_site/db/*"
- "main_site/l10n/*"
- "main_site/images/*"
- "main_site/fonts/*"
- "main_site/js/directives/*"
- "main_site/js/app/*"
- "main_site/js/services/*"
- "main_site/js/others/*"
- "main_site/js/controllers/bootstrap.js"
# excluding paths of admin directory
- "admin/api/*"
- "admin/vendor/*"
- "admin/psd/*"
- "admin/fonts/*"
- "admin/l10n/*"
- "admin/fonts/*"
- "admin/img/*"
- "admin/js/directives/*"
- "admin/js/app/*"
- "admin/js/services/*"
- "admin/js/others/*"
- "admin/js/controllers/bootstrap.js"

