# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: true
  JavaScript: true
  PHP: true
  Python: true
 exclude_paths:
- uploads/*
- uploads_verified/*
- db/*
- api/Slim/*
- api/NotORM/*
- seller/vendor/*
- main_site/vendor/*
# - "foo/bar.rb"
